# -*- coding: utf-8 -*-
"""main v2.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qjI3siUZBOhX8bZ-J1eBnzEiYEfcGt8T
"""

# main.py
from transaction import Transaction

trx1 = Transaction()
'''
Test Case 1
Customer ingin menambahkan 2 item baru
'''
print("Test Case 1")
print("-----------")

# tambah item 1
trx1.add_item()
print("")

# tambah item 2
trx1.add_item()
print("")

'''
Test Case 2
Customer ingin menghapus item yang sudah dibeli
'''
print("Test Case 2")
print("-----------")

# hapus item pasta gigi
trx1.delete_item("Pasta Gigi")
print("")

'''
Test Case 3
Customer ingin menghapus seluruh item yang sudah dibeli
'''
print("Test Case 3")
print("-----------")

# hapus item pasta gigi
trx1.reset_transaction()
print("")

'''
Test Case 4
Customer ingin menampilkan daftar belanjaan yang dibeli dan melihat harga total belanja
'''
print("Test Case 4")
print("-----------")

# tambah item 1
trx1.add_item()
print("")

# tambah item 2
trx1.add_item()
print("")

# tambah item 3
trx1.add_item()
print("")

# tambah item 4
trx1.add_item()
print("")

# melakukan pengecakan rincian belanja
trx1.check_order()

# menghitung total belanja
trx1.total_price()

'''
Test Case 5
Test case tambahan untuk melakukan uji coba fungsi update name, update qty, update price
'''
print("Test Case 5")
print("-----------")

# update item name
trx1.update_item_name("Ayam Goreng", "Ayam Geprek")
print("")

# update item qty
trx1.update_item_qty("Pasta Gigi", 10)
print("")

# update item price
trx1.update_item_price("Mainan Mobil", 300_000)
print("")

# melakukan pengecakan rincian belanja
trx1.check_order()

# menghitung total belanja
trx1.total_price()